java-src/io/github/erdos/stencil/impl/ClojureHelper.java, src/stencil/infix.clj, src/stencil/merger.clj, src/stencil/postprocess/delayed.clj, src/stencil/postprocess/whitespaces.clj, src/stencil/process.clj, src/stencil/tree_postprocess.clj, src/stencil/types.clj, test/stencil/api_test.clj, test/stencil/errors.clj, test/stencil/postprocess/whitespaces_test.clj, test/stencil/process_test.clj, test/stencil/tree_postprocess_test.clj
In some cases whitespace characters disappear around substitutions in Microsoft Office Word.
For example consider the following dummy xml content:
```
<a>Amount: {%=x</a><a>%} pieces</a>
```
After substitution it gives:
```
<a>Amount: 23</a><a> pieces</a>
```
The second `<a>` starts with a whitespace character, however, Word does not display that.
This bugfix works the following way:
- In a postprocess steps it looks for `t` elements with text content starting or ending with a whitespace character and adds an `xml:whitespace=preserve` attribute to them.
=> bugfix: some whitespaces disappear around substitution expressions

src/stencil/infix.clj, test/stencil/infix_test.clj
resolves #7 by introducing operator precedences in the Shinging Yard algorithm in `infix.clj` file.
=> fix error on double logical negation

java-src/io/github/erdos/stencil/impl/FileHelper.java, src/stencil/process.clj
On windows machines the generated docx files contain file paths with backslash (`\`) file separators. This bugfix enforces the use of `/` characters instead. See #20 for details.
=> windows support

build-native-image.sh, java-src/io/github/erdos/stencil/EvaluatedDocument.java, java-src/io/github/erdos/stencil/Main.java, java-src/io/github/erdos/stencil/impl/ClojureHelper.java, java-src/io/github/erdos/stencil/impl/NativeEvaluator.java, src/stencil/api.clj, src/stencil/model.clj, src/stencil/process.clj
this change removes the usage of parallelism by eliminating `future` calls in `process.clj`.
1. This lets us remove multithreading from the compiled `native-image` version of the standalone application reducing executable file size by about _4%_ and runtime by _almost 50%_.
2. Removes the need to call `(shutdown-agents)` after using the library to shut down Clojure's agent thread pools.
=> performance improvements by removing parallelism

java-src/io/github/erdos/stencil/functions/DateFunctions.java
Package `javax.xml.bind` was removed in JDK 11, so even if the source and target are 1.8, the project could not be built with the current LTS JDK.
The change uses `DataTypeFactory.newXMLGregorianCalendar` to try to parse the possible date string.
=> JDK11 removed javax.xml.bind

service/Dockerfile
My name is Eugene, I're exploring the possibility of using stencil in Contractbook, the company I work for. When trying to build an image, I've stumbled upon an issue.
With clojure base image tagged as "latest", it is not possible to build that image. The following error is returned:
```
Step 6/15 : RUN mv "$(lein uberjar | sed -n 's/^Created \(.*standalone\.jar\)/\1/p')" myapp-standalone.jar
---> Running in 288116953c6e
Compiling stencil.service.core
java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(server.clj:1:1)
Exception in thread "main" java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(server.clj:1:1)
at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3700)
...
Caused by: java.lang.ClassNotFoundException: …
```
=> Pin clojure build image to an older tag

java-src/io/github/erdos/stencil/EvaluatedDocument.java, java-src/io/github/erdos/stencil/impl/InputStreamExceptionPropagation.java
Fixes https://github.com/erdos/stencil/issues/34 by wrapping the produced `InputStream` in a proxy that throws the wrapped exception on the `.close()` method call.
=> fix: propagate exception on EvaluatedDocument.toInputStream

README.md, project.clj, service/project.clj, src/stencil/model.clj, src/stencil/model/numbering.clj, src/stencil/util.clj
Processing templates may throw exception when lazy xml tree is not yet evaluated but input stream has already been closed.
=> release version 0.3.13, fix error on closed input stream

README.md, docs/Functions.md, project.clj, service/project.clj, src/stencil/functions.clj, test/stencil/functions_test.clj
Adds `decimal()` and `integer()` functions that can be used to get consistent results with `format()` function.
Relates to https://github.com/erdos/stencil/issues/71
=> feat: version 0.3.17 - add decimal and integer functions

docs/Functions.md, src/stencil/functions.clj, test/stencil/functions_test.clj
See https://github.com/erdos/stencil/issues/76
Adds `formatWithLocale()` function that is similar to `format()` but first argument is IETF Language Tag.
=> feat: formatWithLocale function

docs/Functions.md
Markdown to HTML convertion tool generates header ids in lowercase
=> Fix link reference to the formatWithLocale function

docs/Functions.md, java-src/io/github/erdos/stencil/functions/DateFunctions.java, test/stencil/functions_test.clj
See Issue: https://github.com/erdos/stencil/issues/89
Adds a 3-arity version of `date()` function to render localized strings.
=> feat: localize date function

docs/Functions.md, src/stencil/functions.clj, test/stencil/functions_test.clj
Add new `list()` function to create a sequential collection (Clojure vector).
=> feat: add list function

docs/Syntax.md, src/stencil/infix.clj, test/stencil/infix_test.clj
Add the new  bracket operator to access fields with unexpected syntax.
Example: Use `a['x-y']` to access `a.x-y`.
=> feat: array access operator

src/stencil/ooxml.clj
The `http://schemas.microsoft.com/office/word/2010/wordprocessingGroup` namespace is expected to have an alias of `wpg` by LO 6.4. Having a different alias caused LibreOffice to not display grouped drawings.
I added some additional default namespace aliases from sample files also, to hopefully prevent some later errors caused by this.
A previous issue and PR with the same main cause: #55, #56
=> Additional default OOXML namespace aliases

README.md, project.clj, service/project.clj, src/stencil/functions.clj
see https://github.com/erdos/stencil/issues/120
=> feat: version 0.4.1

docs/Functions.md, src/stencil/functions.clj, src/stencil/ooxml.clj
Implementation for https://github.com/erdos/stencil/issues/124
=> feat: pageBreak function

docs/Syntax.md, src/stencil/eval.clj, src/stencil/tokenizer.clj, test/stencil/eval_test.clj, test/stencil/tokenizer_test.clj
=> feat: foreach construct

docs/Functions.md, src/stencil/functions.clj, test/stencil/functions_test.clj
Implement `replace()` function. See https://github.com/erdos/stencil/issues/133
=> feat: replace fn

src/stencil/ooxml.clj, src/stencil/postprocess/fragments.clj, test/stencil/postprocess/fragments_test.clj
text runs were droppen when they were in the same `w:p` elem where the fragment include expression was.
=> fix: fragments dropped environment

src/stencil/merger.clj, test/stencil/merger_test.clj
There is a bug in the merger algorithm causing some templates to crash stencil.
It is a miracle it has not came up earlier.
=> fix: merger substring exception

src/stencil/infix.clj, src/stencil/postprocess/list_ref.clj, src/stencil/tokenizer.clj, src/stencil/util.clj, test/stencil/tokenizer_test.clj, test/stencil/util_test.clj
As mentioned in  https://github.com/erdos/stencil/issues/139#issuecomment-1321698516
> The most nasty issue we've got probably. We've had a long DOCX template which included {% end %} tag that contained a Non-breaking space between d and % which failed the rendering. It was only returning stencil.exceptions.ParsingException: Unexpected command I believe.
Apparently, `java.lang.Character/isWhitespace` is `false` for non-breaking whitepsace and therefore `java.lang.String/trim` also does not work on it. It produces cryptic error messages so lets fix it properly.
=> fix: nonbreaking space in control

README.md, project.clj, service/project.clj
=> feat: bump 0.5.0

.gitignore, src/stencil/cleanup.clj, src/stencil/model.clj, test/stencil/errors.clj, test/stencil/process_test.clj
Allow arbitrary expressions in fragment include directives.
https://github.com/erdos/stencil/issues/153
=> feat: allow expression in fragment include directives

src/stencil/model.clj, src/stencil/model/fragments.clj
small refactor: extract fragment handling into its own namespace
=> feat: fragment context

build.clj, docs/Functions.md, java-src/io/github/erdos/stencil/API.java, java-src/io/github/erdos/stencil/functions/BasicFunctions.java, java-src/io/github/erdos/stencil/functions/DateFunctions.java, java-src/io/github/erdos/stencil/functions/FunctionEvaluator.java, java-src/io/github/erdos/stencil/functions/FunctionsProvider.java, java-src/io/github/erdos/stencil/functions/LocaleFunctions.java, java-src/io/github/erdos/stencil/functions/NumberFunctions.java, java-src/io/github/erdos/stencil/functions/StringFunctions.java
Reimplements https://github.com/erdos/stencil/pull/138 
and resolves conflicts with code changed in the meanwhile. We aim to keep the code simpler this time:
- no function priorities - to keep code simple. We do not allow overriding of functions (by same name) but instead just throw an exception when function with same name already exists.
- small footprint in code diff (ideally below 100 LOC)
- automatic configuration generation (in META-INF)
Scenarios to manually test:
=> functions provider SPI
